/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'project-categories': ProjectCategory;
    projects: Project;
    services: Service;
    sectors: Sector;
    capabilities: Capability;
    testimonials: Testimonial;
    certifications: Certification;
    enquiries: Enquiry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'project-categories': ProjectCategoriesSelect<false> | ProjectCategoriesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    sectors: SectorsSelect<false> | SectorsSelect<true>;
    capabilities: CapabilitiesSelect<false> | CapabilitiesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    certifications: CertificationsSelect<false> | CertificationsSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    homepage: Homepage;
    'about-page': AboutPage;
    'contact-page': ContactPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'super-admin' | 'editor' | 'enquiry-manager';
  active?: boolean | null;
  profileImage?: (number | null) | Media;
  phone?: string | null;
  lastLoginAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for visitors using assistive technology.
   */
  alt: string;
  title: string;
  caption?: string | null;
  photographer?: string | null;
  project?: (number | null) | Project;
  category?: ('Project' | 'Company' | 'Team' | 'Certification' | 'Website' | 'Document') | null;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    gallery?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * URL-safe identifier. It is generated automatically but can be edited.
   */
  slug: string;
  shortSummary: string;
  category: number | ProjectCategory;
  location: string;
  district?: string | null;
  year?: string | null;
  status: 'ongoing' | 'completed' | 'upcoming';
  clientType?: string | null;
  featured?: boolean | null;
  displayOrder?: number | null;
  publishedAt?: string | null;
  scopeOfWork?: string | null;
  contractType?: string | null;
  builtUpArea?: string | null;
  duration?: string | null;
  startDate?: string | null;
  completionDate?: string | null;
  projectValue?: {
    value?: string | null;
    /**
     * Enable only after the company has approved public disclosure.
     */
    displayPublicly?: boolean | null;
  };
  architectConsultant?: string | null;
  executionResponsibilities?: string | null;
  materials?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  constructionMethods?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  qualityControl?: string | null;
  safetyInformation?: string | null;
  overview: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  challenge?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  executionApproach?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  outcome?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  qualityAndSafety?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  additionalNotes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage: number | Media;
  heroImage?: (number | null) | Media;
  /**
   * Drag rows to control gallery order.
   */
  gallery?:
    | {
        media: number | Media;
        caption?: string | null;
        altOverride?: string | null;
        displayOrder?: number | null;
        layout?: ('standard' | 'wide' | 'portrait') | null;
        id?: string | null;
      }[]
    | null;
  beforeAfter?:
    | {
        before: number | Media;
        after: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  documents?: (number | Media)[] | null;
  services?: (number | Service)[] | null;
  sectors?: (number | Sector)[] | null;
  relatedProjects?: (number | Project)[] | null;
  /**
   * Optional overrides. Site defaults are used when fields are empty.
   */
  seo?: {
    /**
     * Aim for 50–60 characters.
     */
    title?: string | null;
    /**
     * Aim for 140–160 characters.
     */
    description?: string | null;
    image?: (number | null) | Media;
    canonicalURL?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-categories".
 */
export interface ProjectCategory {
  id: number;
  name: string;
  /**
   * URL-safe identifier. It is generated automatically but can be edited.
   */
  slug: string;
  description?: string | null;
  displayOrder?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  /**
   * URL-safe identifier. It is generated automatically but can be edited.
   */
  slug: string;
  shortDescription: string;
  fullDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Use a supported Lucide icon name, e.g. Building2.
   */
  icon?: string | null;
  coverImage?: (number | null) | Media;
  capabilities?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  typicalScope?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  relevantProjectTypes?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  relatedProjects?: (number | Project)[] | null;
  featured?: boolean | null;
  displayOrder?: number | null;
  active?: boolean | null;
  /**
   * Optional overrides. Site defaults are used when fields are empty.
   */
  seo?: {
    /**
     * Aim for 50–60 characters.
     */
    title?: string | null;
    /**
     * Aim for 140–160 characters.
     */
    description?: string | null;
    image?: (number | null) | Media;
    canonicalURL?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectors".
 */
export interface Sector {
  id: number;
  name: string;
  /**
   * URL-safe identifier. It is generated automatically but can be edited.
   */
  slug: string;
  description?: string | null;
  image?: (number | null) | Media;
  icon?: string | null;
  relatedProjects?: (number | Project)[] | null;
  displayOrder?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "capabilities".
 */
export interface Capability {
  id: number;
  name: string;
  shortDescription: string;
  detailedDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  icon?: string | null;
  image?: (number | null) | Media;
  displayOrder?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  text: string;
  personName?: string | null;
  designation?: string | null;
  organisation?: string | null;
  clientType?: string | null;
  image?: (number | null) | Media;
  relatedProject?: (number | null) | Project;
  /**
   * Keep enabled until the testimonial and client attribution are approved.
   */
  isPlaceholder?: boolean | null;
  featured?: boolean | null;
  displayOrder?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications".
 */
export interface Certification {
  id: number;
  name: string;
  issuingAuthority?: string | null;
  registrationNumber?: string | null;
  issueDate?: string | null;
  expiryDate?: string | null;
  document?: (number | null) | Media;
  logo?: (number | null) | Media;
  /**
   * Controls whether the registration number and document may be public.
   */
  showDetailsPublicly?: boolean | null;
  publiclyVisible?: boolean | null;
  displayOrder?: number | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  reference: string;
  fullName: string;
  phone: string;
  email?: string | null;
  organisation?: string | null;
  projectType: string;
  projectLocation?: string | null;
  district?: string | null;
  estimatedBudget?: string | null;
  expectedStartDate?: string | null;
  message: string;
  sourcePage?: string | null;
  relatedProject?: (number | null) | Project;
  relatedService?: (number | null) | Service;
  status:
    | 'new'
    | 'contacted'
    | 'site-visit-planned'
    | 'proposal-in-progress'
    | 'proposal-sent'
    | 'won'
    | 'lost'
    | 'closed'
    | 'spam';
  assignedAdministrator?: (number | null) | User;
  priority?: ('low' | 'normal' | 'high' | 'urgent') | null;
  internalNotes?: string | null;
  lastContactedAt?: string | null;
  consentConfirmed: boolean;
  tracking?: {
    utmSource?: string | null;
    utmMedium?: string | null;
    utmCampaign?: string | null;
    utmTerm?: string | null;
    utmContent?: string | null;
    referrer?: string | null;
  };
  emailNotificationStatus?: ('pending' | 'sent' | 'failed' | 'skipped') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'project-categories';
        value: number | ProjectCategory;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'sectors';
        value: number | Sector;
      } | null)
    | ({
        relationTo: 'capabilities';
        value: number | Capability;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'certifications';
        value: number | Certification;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  active?: T;
  profileImage?: T;
  phone?: T;
  lastLoginAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  title?: T;
  caption?: T;
  photographer?: T;
  project?: T;
  category?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        gallery?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-categories_select".
 */
export interface ProjectCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  displayOrder?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortSummary?: T;
  category?: T;
  location?: T;
  district?: T;
  year?: T;
  status?: T;
  clientType?: T;
  featured?: T;
  displayOrder?: T;
  publishedAt?: T;
  scopeOfWork?: T;
  contractType?: T;
  builtUpArea?: T;
  duration?: T;
  startDate?: T;
  completionDate?: T;
  projectValue?:
    | T
    | {
        value?: T;
        displayPublicly?: T;
      };
  architectConsultant?: T;
  executionResponsibilities?: T;
  materials?:
    | T
    | {
        name?: T;
        id?: T;
      };
  constructionMethods?:
    | T
    | {
        name?: T;
        id?: T;
      };
  qualityControl?: T;
  safetyInformation?: T;
  overview?: T;
  challenge?: T;
  executionApproach?: T;
  outcome?: T;
  qualityAndSafety?: T;
  additionalNotes?: T;
  coverImage?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        media?: T;
        caption?: T;
        altOverride?: T;
        displayOrder?: T;
        layout?: T;
        id?: T;
      };
  beforeAfter?:
    | T
    | {
        before?: T;
        after?: T;
        caption?: T;
        id?: T;
      };
  documents?: T;
  services?: T;
  sectors?: T;
  relatedProjects?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalURL?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  shortDescription?: T;
  fullDescription?: T;
  icon?: T;
  coverImage?: T;
  capabilities?:
    | T
    | {
        label?: T;
        id?: T;
      };
  typicalScope?: T;
  relevantProjectTypes?:
    | T
    | {
        label?: T;
        id?: T;
      };
  relatedProjects?: T;
  featured?: T;
  displayOrder?: T;
  active?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalURL?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectors_select".
 */
export interface SectorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  image?: T;
  icon?: T;
  relatedProjects?: T;
  displayOrder?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "capabilities_select".
 */
export interface CapabilitiesSelect<T extends boolean = true> {
  name?: T;
  shortDescription?: T;
  detailedDescription?: T;
  icon?: T;
  image?: T;
  displayOrder?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  text?: T;
  personName?: T;
  designation?: T;
  organisation?: T;
  clientType?: T;
  image?: T;
  relatedProject?: T;
  isPlaceholder?: T;
  featured?: T;
  displayOrder?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications_select".
 */
export interface CertificationsSelect<T extends boolean = true> {
  name?: T;
  issuingAuthority?: T;
  registrationNumber?: T;
  issueDate?: T;
  expiryDate?: T;
  document?: T;
  logo?: T;
  showDetailsPublicly?: T;
  publiclyVisible?: T;
  displayOrder?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  reference?: T;
  fullName?: T;
  phone?: T;
  email?: T;
  organisation?: T;
  projectType?: T;
  projectLocation?: T;
  district?: T;
  estimatedBudget?: T;
  expectedStartDate?: T;
  message?: T;
  sourcePage?: T;
  relatedProject?: T;
  relatedService?: T;
  status?: T;
  assignedAdministrator?: T;
  priority?: T;
  internalNotes?: T;
  lastContactedAt?: T;
  consentConfirmed?: T;
  tracking?:
    | T
    | {
        utmSource?: T;
        utmMedium?: T;
        utmCampaign?: T;
        utmTerm?: T;
        utmContent?: T;
        referrer?: T;
      };
  emailNotificationStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  fullCompanyName: string;
  shortCompanyName: string;
  tagline: string;
  companyDescription: string;
  contractorClassification: string;
  logo?: (number | null) | Media;
  alternateLogo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  phoneNumbers?:
    | {
        label: string;
        number: string;
        id?: string | null;
      }[]
    | null;
  whatsappNumber?: string | null;
  emailAddresses?:
    | {
        label: string;
        email: string;
        id?: string | null;
      }[]
    | null;
  officeAddress?: string | null;
  googleMapsURL?: string | null;
  businessHours?: string | null;
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  enquiryNotificationEmail?: string | null;
  registrationDetails?: {
    contractorRegistration?: string | null;
    gstNumber?: string | null;
    /**
     * Enable only after details have been verified and approved.
     */
    displayPublicly?: boolean | null;
  };
  navigation?:
    | {
        label: string;
        url: string;
        newTab?: boolean | null;
        visible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  primaryCTA: {
    label: string;
    url: string;
    newTab?: boolean | null;
    id?: string | null;
  };
  footerDescription?: string | null;
  footerNavigationGroups?:
    | {
        label: string;
        links?:
          | {
              label: string;
              url: string;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footerCTA: {
    eyebrow?: string | null;
    heading?: string | null;
    label: string;
    url: string;
    newTab?: boolean | null;
  };
  copyrightText?: string | null;
  footerRegistrationText?: string | null;
  announcement?: {
    visible?: boolean | null;
    message?: string | null;
    url?: string | null;
  };
  /**
   * Optional overrides. Site defaults are used when fields are empty.
   */
  seo?: {
    /**
     * Aim for 50–60 characters.
     */
    title?: string | null;
    /**
     * Aim for 140–160 characters.
     */
    description?: string | null;
    image?: (number | null) | Media;
    canonicalURL?: string | null;
    noIndex?: boolean | null;
  };
  /**
   * Canonical public website origin, without a trailing slash.
   */
  productionURL: string;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  heroEyebrow: string;
  heroHeading: string;
  heroAccent?: string | null;
  heroSupportingText: string;
  heroImage: number | Media;
  heroVideo?: (number | null) | Media;
  primaryCTA: {
    label: string;
    url: string;
    newTab?: boolean | null;
    id?: string | null;
  };
  secondaryCTA: {
    label: string;
    url: string;
    newTab?: boolean | null;
    id?: string | null;
  };
  introductoryStatement: string;
  featuredProjects?: (number | Project)[] | null;
  featuredServices?: (number | Service)[] | null;
  featuredSectors?: (number | Sector)[] | null;
  statistics?:
    | {
        value: string;
        label: string;
        verified?: boolean | null;
        id?: string | null;
      }[]
    | null;
  whySection?: {
    eyebrow?: string | null;
    heading?: string | null;
    introduction?: string | null;
    image?: (number | null) | Media;
    points?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  constructionProcess?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  testimonials?: (number | Testimonial)[] | null;
  finalCTA: {
    heading?: string | null;
    supportingText?: string | null;
    label: string;
    url: string;
    newTab?: boolean | null;
  };
  sectionVisibility?: {
    statistics?: boolean | null;
    projects?: boolean | null;
    services?: boolean | null;
    why?: boolean | null;
    process?: boolean | null;
    sectors?: boolean | null;
    testimonials?: boolean | null;
  };
  /**
   * Optional overrides. Site defaults are used when fields are empty.
   */
  seo?: {
    /**
     * Aim for 50–60 characters.
     */
    title?: string | null;
    /**
     * Aim for 140–160 characters.
     */
    description?: string | null;
    image?: (number | null) | Media;
    canonicalURL?: string | null;
    noIndex?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  hero: {
    eyebrow: string;
    heading: string;
    introduction: string;
    image?: (number | null) | Media;
  };
  companyIntroduction: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  history?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  mission?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  vision?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  values?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  leadershipContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  timeline?:
    | {
        year: string;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  regionalExperience?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  qualityCommitment?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  safetyCommitment?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  teamImages?: (number | Media)[] | null;
  cta: {
    label: string;
    url: string;
    newTab?: boolean | null;
    id?: string | null;
  };
  /**
   * Optional overrides. Site defaults are used when fields are empty.
   */
  seo?: {
    /**
     * Aim for 50–60 characters.
     */
    title?: string | null;
    /**
     * Aim for 140–160 characters.
     */
    description?: string | null;
    image?: (number | null) | Media;
    canonicalURL?: string | null;
    noIndex?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  hero: {
    eyebrow: string;
    heading: string;
    introduction: string;
    image?: (number | null) | Media;
  };
  officeHeading?: string | null;
  officeInformation?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  mapEmbedURL?: string | null;
  enquiryCategories?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  formSupportingText?: string | null;
  whatsappCTA: {
    label: string;
    url: string;
    newTab?: boolean | null;
    message?: string | null;
  };
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional overrides. Site defaults are used when fields are empty.
   */
  seo?: {
    /**
     * Aim for 50–60 characters.
     */
    title?: string | null;
    /**
     * Aim for 140–160 characters.
     */
    description?: string | null;
    image?: (number | null) | Media;
    canonicalURL?: string | null;
    noIndex?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  fullCompanyName?: T;
  shortCompanyName?: T;
  tagline?: T;
  companyDescription?: T;
  contractorClassification?: T;
  logo?: T;
  alternateLogo?: T;
  favicon?: T;
  phoneNumbers?:
    | T
    | {
        label?: T;
        number?: T;
        id?: T;
      };
  whatsappNumber?: T;
  emailAddresses?:
    | T
    | {
        label?: T;
        email?: T;
        id?: T;
      };
  officeAddress?: T;
  googleMapsURL?: T;
  businessHours?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  enquiryNotificationEmail?: T;
  registrationDetails?:
    | T
    | {
        contractorRegistration?: T;
        gstNumber?: T;
        displayPublicly?: T;
      };
  navigation?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        visible?: T;
        id?: T;
      };
  primaryCTA?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  footerDescription?: T;
  footerNavigationGroups?:
    | T
    | {
        label?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  footerCTA?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        label?: T;
        url?: T;
        newTab?: T;
      };
  copyrightText?: T;
  footerRegistrationText?: T;
  announcement?:
    | T
    | {
        visible?: T;
        message?: T;
        url?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalURL?: T;
        noIndex?: T;
      };
  productionURL?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroHeading?: T;
  heroAccent?: T;
  heroSupportingText?: T;
  heroImage?: T;
  heroVideo?: T;
  primaryCTA?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  secondaryCTA?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  introductoryStatement?: T;
  featuredProjects?: T;
  featuredServices?: T;
  featuredSectors?: T;
  statistics?:
    | T
    | {
        value?: T;
        label?: T;
        verified?: T;
        id?: T;
      };
  whySection?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        introduction?: T;
        image?: T;
        points?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  constructionProcess?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  testimonials?: T;
  finalCTA?:
    | T
    | {
        heading?: T;
        supportingText?: T;
        label?: T;
        url?: T;
        newTab?: T;
      };
  sectionVisibility?:
    | T
    | {
        statistics?: T;
        projects?: T;
        services?: T;
        why?: T;
        process?: T;
        sectors?: T;
        testimonials?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalURL?: T;
        noIndex?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        introduction?: T;
        image?: T;
      };
  companyIntroduction?: T;
  history?: T;
  mission?: T;
  vision?: T;
  values?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  leadershipContent?: T;
  timeline?:
    | T
    | {
        year?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  regionalExperience?: T;
  qualityCommitment?: T;
  safetyCommitment?: T;
  teamImages?: T;
  cta?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalURL?: T;
        noIndex?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        introduction?: T;
        image?: T;
      };
  officeHeading?: T;
  officeInformation?: T;
  mapEmbedURL?: T;
  enquiryCategories?:
    | T
    | {
        label?: T;
        id?: T;
      };
  formSupportingText?: T;
  whatsappCTA?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        message?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalURL?: T;
        noIndex?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}